<!DOCTYPE HTML>

<html>
<head>
	<meta charset="UTF-8">
	<title>Search By Logo</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
	<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
</head>

<body>
	<div id="header">
		<div>
			<ul id="navigation">
				<li class="active">
				<div>
					<h2>Search By Logo</h2>
				</div>
				</li>
				
			</ul>
		</div>
	</div>
	<div id="adbox">
		<div class="clearfix">
			
			<div>
				<h1></h1>
				<h3>Upload Your Logo</h3>
				&nbsp;&nbsp;&nbsp;
				
				<p> 
				Search By Logo is an online tool to check whether your logo exists amongst the logos in our database. It provides an easy medium to verify authenticity of your self-designed logos. </p>
				
				<p>
				
				&nbsp;&nbsp;&nbsp;
				<form action="" method="post"
				enctype="multipart/form-data" class="pure-form pure-form-stacked" >
				
				<fieldset>
				
				<tr><input type="file" name="file" id="file" /></tr>
				<tr></tr>
				<tr><input  type="submit" name="submit" value="Submit" ></tr>
				
				</fieldset>
				</form>
							
							
				</p>
				
												
			</div>
			&nbsp;&nbsp;&nbsp;
			
			
		</div>
	</div>
	
	
	
	
	<div id="contents">
		<div class="clearfix">			
				
				<div>
				<h3>Your Logo</h3>
				
				<p>
				
				<img src="image/q_image.jpg" alt="Img" height="120" width="120">
				</p>
				
				</div>
	
	
			
					
				<!-- Code for reading similar images from a text file generated by MatLab      -->

				
				
				<div >
					<h3>Similar Logos</h3>
					
					
				
				
				<?php
					
				
					$t=file_get_contents('textfile.txt');
					$text=explode(",",$t);
				

				for ($i=0; $i<=(count($text)-2); $i++)
					{ 
					
					?>
					<img src= "<?php echo 'exp/'.$text[$i]; ?>" alt="Img" height="120" width="120">
					
						
					<?php
						
					}
					 ?>
				</div>
				
				
			
		</div>
	</div>
	
	
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				
			</p>
		</div>
	</div>
</body>
</html>
